credentials:
  usernames:
    admin:
      email: admin@auraderm.com
      name: Admin User
      password: $2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5aeWG5xJq7JYK  # password: admin123
    demo:
      email: demo@auraderm.com
      name: Demo User
      password: $2b$12$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeG6Lruj3vjPGga31lW  # password: demo123
cookie:
  expiry_days: 30
  key: auraderm_secret_key_12345
  name: auraderm_cookie
preauthorized:
  emails:
    - admin@auraderm.com
